{{- range $serviceName, $serviceSpec := .Values.services -}}
{{- if $serviceSpec.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $serviceName }}-deployment
  namespace: default
  labels:
    app: {{ $serviceName }}
spec:
  replicas: {{ $serviceSpec.replicaCount }}
  selector:
    matchLabels:
      app: {{ $serviceName }}
  template:
    metadata:
      labels:
        app: {{ $serviceName }}
    spec:
      containers:
        - name: web-app
          image: "{{ $.Values.accountId }}.dkr.ecr.{{ $.Values.awsRegion }}.amazonaws.com/{{ $.Values.environment }}-{{ $serviceName }}:latest"
          ports:
            - containerPort: {{ $serviceSpec.port }}
          resources:
            {{- toYaml $serviceSpec.resources | nindent 12 -}}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ $serviceSpec.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: {{ $serviceSpec.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
---
{{- end -}}
{{- end -}}
